### ISSUE TITLE
error:this interaction failed

### ISSUE THREAD

**Issue by ASACHIT** [shinotheshino/remoji-bot#12]
**command used:** **/copy: emotename**  and got this error

![image](https://user-images.githubusercontent.com/73944456/124351541-b6427080-dc1a-11eb-84a0-3c7640ff2f58.png)

**Comment by memikri** [comment]
Thank you for the report. This was due to the server hosting Remoji running out of system memory. I upgraded the server and it should be working now.

**Comment by ASACHIT** [comment]
> Thank you for the report. This was due to the server hosting Remoji running out of system memory. I upgraded the server and it should be working now.

Thank you :) it's working now 🤗
