### ISSUE TITLE
"Error: Command failed: git rev-parse --abbrev-ref HEAD 'git' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by shroomjaks** [shinotheshino/remoji-bot#4]
How can I fix this?

**Comment by memikri** [comment]
Hi @MonkoTubeYT,

You can fix this error by installing Git from https://git-scm.com/download/win

I will update the README to reflect this requirement.

**Comment by shroomjaks** [comment]
I have installed this twice but the problem still persists?

**Comment by memikri** [comment]
If you open a command prompt and type `git`, what appears?
